package com.example.fretboardlayouts.theory

data class DrumPreset(
    val id: String,
    val displayName: String,
    val originalBpm: Int,
    val timeSignature: String,
    val grooveFactor: Float,
    val kickPattern: String,
    val kickVelocity: String,
    val snarePattern: String,
    val snareVelocity: String,
    val hihatPattern: String,
    val hihatVelocity: String
)

/**
 * All drum presets extracted from Groove MIDI Dataset
 * 140 presets across multiple genres
 */
val allDrumPresets = listOf(
DrumPreset(
        id = "afrobeat-13_afrobeat_103_beat_4-4",
        displayName = "13_Afrobeat_103_Beat_4 4",
        originalBpm = 103,
        timeSignature = "4/4",
        grooveFactor = 0.09f,
        kickPattern =   "x______x__x__x__",
        kickVelocity =  "5______4__5__4__",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______9___",
        hihatPattern =  "____x__xx_____x_",
        hihatVelocity = "____3__11_____4_"
    ),
DrumPreset(
        id = "afrobeat-14_afrobeat_103_beat_4-4",
        displayName = "14_Afrobeat_103_Beat_4 4",
        originalBpm = 103,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "____x__x__x__x__",
        kickVelocity =  "____1__4__5__4__",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______9___",
        hihatPattern =  "____x___x______x",
        hihatVelocity = "____3___1______2"
    ),
DrumPreset(
        id = "afrobeat-16_afrobeat_90_beat_4-4",
        displayName = "16_Afrobeat_90_Beat_4 4",
        originalBpm = 90,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "x___x___xx__x___",
        kickVelocity =  "8___9___65__9___",
        snarePattern =  "___x__x____x__x_",
        snareVelocity = "___9__9____9__9_",
        hihatPattern =  "x_____x_x_x___x_",
        hihatVelocity = "3_____4_5_3___4_"
    ),
DrumPreset(
        id = "afrocuban-176_afrocuban_105_beat_4-4",
        displayName = "176_Afrocuban_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "x_______________",
        kickVelocity =  "4_______________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "x__xxxxxxxxxxxxx",
        hihatVelocity = "8__1473463451613"
    ),
DrumPreset(
        id = "afrocuban-183_afrocuban_105_beat_4-4",
        displayName = "183_Afrocuban_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.27f,
        kickPattern =   "___x__x____x__x_",
        kickVelocity =  "___3__3____3__3_",
        snarePattern =  "__xx_x_x_xx__x_x",
        snareVelocity = "__42_2_5_12__2_3",
        hihatPattern =  "x_x_x_x_x_x_x_x_",
        hihatVelocity = "6_5_5_5_5_5_4_5_"
    ),
DrumPreset(
        id = "afrocuban-18_afrocuban_128_beat_4-4",
        displayName = "18_Afrocuban_128_Beat_4 4",
        originalBpm = 128,
        timeSignature = "4/4",
        grooveFactor = 0.28f,
        kickPattern =   "___x____________",
        kickVelocity =  "___3____________",
        snarePattern =  "_x__xx__x_x__x_x",
        snareVelocity = "_3__21__7_4__3_2",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________5___"
    ),
DrumPreset(
        id = "afrocuban-bembe-112_afrocuban-bembe_122_beat_4-4",
        displayName = "112_Afrocuban Bembe_122_Beat_4 4",
        originalBpm = 122,
        timeSignature = "4/4",
        grooveFactor = 0.25f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "___________xx___",
        snareVelocity = "___________98___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "afrocuban-calypso-13_afrocuban-calypso_124_beat_4-4",
        displayName = "13_Afrocuban Calypso_124_Beat_4 4",
        originalBpm = 124,
        timeSignature = "4/4",
        grooveFactor = 0.14f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "3___1___3___3___",
        snarePattern =  "xx_x_______x____",
        snareVelocity = "11_4_______4____",
        hihatPattern =  "______x___x___x_",
        hihatVelocity = "______3___5___5_"
    ),
DrumPreset(
        id = "afrocuban-calypso-17_afrocuban-calypso_108_beat_4-4",
        displayName = "17_Afrocuban Calypso_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________x_",
        snareVelocity = "______________9_",
        hihatPattern =  "________x___x___",
        hihatVelocity = "________3___6___"
    ),
DrumPreset(
        id = "afrocuban-rhumba-161_afrocuban-rhumba_110_beat_4-4",
        displayName = "161_Afrocuban Rhumba_110_Beat_4 4",
        originalBpm = 110,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "blues-shuffle-17_blues-shuffle_72_beat_4-4",
        displayName = "17_Blues Shuffle_72_Beat_4 4",
        originalBpm = 72,
        timeSignature = "4/4",
        grooveFactor = 0.25f,
        kickPattern =   "_______xx__x___x",
        kickVelocity =  "_______23__3___2",
        snarePattern =  "__x_x___x_x_x___",
        snareVelocity = "__1_6___1_1_7___",
        hihatPattern =  "___________x____",
        hihatVelocity = "___________2____"
    ),
DrumPreset(
        id = "blues-shuffle-6_blues-shuffle_134_beat_4-4",
        displayName = "6_Blues Shuffle_134_Beat_4 4",
        originalBpm = 134,
        timeSignature = "4/4",
        grooveFactor = 0.27f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "x_xxx_xxxx_xxx_x",
        snareVelocity = "6_888_7678_888_6",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "blues-shuffle-7_blues-shuffle_134_beat_4-4",
        displayName = "7_Blues Shuffle_134_Beat_4 4",
        originalBpm = 134,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "x__x___xx__x___x",
        kickVelocity =  "5__5___44__4___5",
        snarePattern =  "____x__xx___x_xx",
        snareVelocity = "____9__11___9_31",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "country-10_country_114_beat_4-4",
        displayName = "10_Country_114_Beat_4 4",
        originalBpm = 114,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "4___4___4___4___",
        snarePattern =  "xxxxxxxxxxxxxxxx",
        snareVelocity = "3262325332633363",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "country-80_country_78_beat_4-4",
        displayName = "80_Country_78_Beat_4 4",
        originalBpm = 78,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "x_______________",
        kickVelocity =  "3_______________",
        snarePattern =  "_x__x__x_x__x__x",
        snareVelocity = "_1__8__1_1__9__1",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "dance-breakbeat-80_dance-breakbeat_170_beat_4-4",
        displayName = "80_Dance Breakbeat_170_Beat_4 4",
        originalBpm = 170,
        timeSignature = "4/4",
        grooveFactor = 0.3f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "_______________x",
        snareVelocity = "_______________2",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "dance-breakbeat-81_dance-breakbeat_170_beat_4-4",
        displayName = "81_Dance Breakbeat_170_Beat_4 4",
        originalBpm = 170,
        timeSignature = "4/4",
        grooveFactor = 0.2f,
        kickPattern =   "x_______x_______",
        kickVelocity =  "3_______2_______",
        snarePattern =  "____x_____x_____",
        snareVelocity = "____5_____5_____",
        hihatPattern =  "xx_x_xxxx__xxxxx",
        hihatVelocity = "43_1_2234__34423"
    ),
DrumPreset(
        id = "dance-disco-101_dance-disco_120_beat_4-4",
        displayName = "101_Dance Disco_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.1f,
        kickPattern =   "x_x_x___x___x___",
        kickVelocity =  "5_1_5___5___5___",
        snarePattern =  "____xx_x__x_x__x",
        snareVelocity = "____72_2__1_6__2",
        hihatPattern =  "x___x___x___x_x_",
        hihatVelocity = "6___4___3___5_5_"
    ),
DrumPreset(
        id = "dance-disco-26_dance-disco_137_beat_4-4",
        displayName = "26_Dance Disco_137_Beat_4 4",
        originalBpm = 137,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "x__x____x__x_x__",
        kickVelocity =  "6__4____5__4_5__",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______9___",
        hihatPattern =  "__x___x___xx_xxx",
        hihatVelocity = "__2___3___43_445"
    ),
DrumPreset(
        id = "dance-disco-27_dance-disco_137_beat_4-4",
        displayName = "27_Dance Disco_137_Beat_4 4",
        originalBpm = 137,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "________x__x_x__",
        kickVelocity =  "________4__4_4__",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______8___",
        hihatPattern =  "_xxx_xxx_xx___xx",
        hihatVelocity = "_222_234_32___34"
    ),
DrumPreset(
        id = "funk-12_funk_102_beat_4-4",
        displayName = "12_Funk_102_Beat_4 4",
        originalBpm = 102,
        timeSignature = "4/4",
        grooveFactor = 0.09f,
        kickPattern =   "_______x__xx____",
        kickVelocity =  "_______7__23____",
        snarePattern =  "____xxx__x__xx_x",
        snareVelocity = "____975__5__93_4",
        hihatPattern =  "________x_x_x_xx",
        hihatVelocity = "________2_2_5_34"
    ),
DrumPreset(
        id = "funk-18_funk_108_beat_4-4",
        displayName = "18_Funk_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.07f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "funk-19_funk_108_beat_4-4",
        displayName = "19_Funk_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "x_________x_____",
        kickVelocity =  "6_________6_____",
        snarePattern =  "____x__x_x_x__xx",
        snareVelocity = "____8__2_4_2__92",
        hihatPattern =  "_______x____x___",
        hihatVelocity = "_______4____2___"
    ),
DrumPreset(
        id = "funk-fast-126_funk-fast_125_beat_4-4",
        displayName = "126_Funk Fast_125_Beat_4 4",
        originalBpm = 125,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "_____________x__",
        kickVelocity =  "_____________4__",
        snarePattern =  "________xxxxx__x",
        snareVelocity = "________31469__3",
        hihatPattern =  "____x_x_x_x_x___",
        hihatVelocity = "____3_3_5_5_6___"
    ),
DrumPreset(
        id = "funk-groove1-1_funk-groove1_138_beat_4-4",
        displayName = "1_Funk Groove1_138_Beat_4 4",
        originalBpm = 138,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x_xx______xx____",
        kickVelocity =  "3_31______23____",
        snarePattern =  "____x__x_x__x__x",
        snareVelocity = "____8__4_4__8__4",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "4___5___5___5___"
    ),
DrumPreset(
        id = "funk-groove2-2_funk-groove2_105_beat_4-4",
        displayName = "2_Funk Groove2_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.31f,
        kickPattern =   "x_______xxx_____",
        kickVelocity =  "3_______313_____",
        snarePattern =  "__x_x___x_x_x___",
        snareVelocity = "__1_9___1_1_9___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "funk-groove5-5_funk-groove5_84_beat_4-4",
        displayName = "5_Funk Groove5_84_Beat_4 4",
        originalBpm = 84,
        timeSignature = "4/4",
        grooveFactor = 0.22f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "x_xxxx_xx_xxxxxx",
        snareVelocity = "4_2841_42_319793",
        hihatPattern =  "___x________x___",
        hihatVelocity = "___5________5___"
    ),
DrumPreset(
        id = "funk-latin-24_funk-latin_100_beat_4-4",
        displayName = "24_Funk Latin_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.12f,
        kickPattern =   "x___xx_x________",
        kickVelocity =  "7___14_5________",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______9___",
        hihatPattern =  "x_x___x___x___x_",
        hihatVelocity = "6_1___2___1___1_"
    ),
DrumPreset(
        id = "funk-latin-25_funk-latin_100_beat_4-4",
        displayName = "25_Funk Latin_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "x____x_x________",
        kickVelocity =  "9____4_9________",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______9___",
        hihatPattern =  "x_x___x___x___x_",
        hihatVelocity = "7_2___2___2___2_"
    ),
DrumPreset(
        id = "funk-purdieshuffle-239_funk-purdieshuffle_130_beat_4-4",
        displayName = "239_Funk Purdieshuffle_130_Beat_4 4",
        originalBpm = 130,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "_______________x",
        kickVelocity =  "_______________3",
        snarePattern =  "______xxx__xx___",
        snareVelocity = "______229__78___",
        hihatPattern =  "____x___x___x___",
        hihatVelocity = "____2___5___5___"
    ),
DrumPreset(
        id = "gospel-142_gospel_120_beat_4-4",
        displayName = "142_Gospel_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.2f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "_____________xx_",
        snareVelocity = "_____________99_",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________2___"
    ),
DrumPreset(
        id = "highlife-41_highlife_126_beat_4-4",
        displayName = "41_Highlife_126_Beat_4 4",
        originalBpm = 126,
        timeSignature = "4/4",
        grooveFactor = 0.12f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "5___5___5___5___",
        snarePattern =  "x_x_____________",
        snareVelocity = "3_1_____________",
        hihatPattern =  "x_x_xxxxx_x_xxxx",
        hihatVelocity = "4_3_33634_4_3453"
    ),
DrumPreset(
        id = "highlife-42_highlife_126_beat_4-4",
        displayName = "42_Highlife_126_Beat_4 4",
        originalBpm = 126,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "4___4___4___4___",
        snarePattern =  "xxxx__x_xx_x__x_",
        snareVelocity = "8223__4_65_6__6_",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___5___5___5_"
    ),
DrumPreset(
        id = "hiphop-14_hiphop_94_beat_4-4",
        displayName = "14_Hiphop_94_Beat_4 4",
        originalBpm = 94,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "x_________x_____",
        kickVelocity =  "5_________5_____",
        snarePattern =  "____x_xx_x____x_",
        snareVelocity = "____9_22_3____9_",
        hihatPattern =  "__x_________x___",
        hihatVelocity = "__1_________1___"
    ),
DrumPreset(
        id = "hiphop-15_hiphop_94_beat_4-4",
        displayName = "15_Hiphop_94_Beat_4 4",
        originalBpm = 94,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "x_______x_x_____",
        kickVelocity =  "6_______4_6_____",
        snarePattern =  "____x_xxxx____x_",
        snareVelocity = "____9_2323____9_",
        hihatPattern =  "__x_x_x_x_x_x___",
        hihatVelocity = "__1_4_1_2_4_1___"
    ),
DrumPreset(
        id = "hiphop-16_hiphop_100_beat_4-4",
        displayName = "16_Hiphop_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "x_x___x_x__x___x",
        kickVelocity =  "6_5___4_4__4___5",
        snarePattern =  "____________xx__",
        snareVelocity = "____________74__",
        hihatPattern =  "__xx_xxx_xx___x_",
        hihatVelocity = "__12_422_31___2_"
    ),
DrumPreset(
        id = "hiphop-groove6-6_hiphop-groove6_87_beat_4-4",
        displayName = "6_Hiphop Groove6_87_Beat_4 4",
        originalBpm = 87,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "x______x_xx__x_x",
        kickVelocity =  "3______3_23__3_2",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______8___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-14_jazz_100_beat_4-4",
        displayName = "14_Jazz_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "_______________x",
        snareVelocity = "_______________2",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____4_______4___"
    ),
DrumPreset(
        id = "jazz-15_jazz_112_beat_4-4",
        displayName = "15_Jazz_112_Beat_4 4",
        originalBpm = 112,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "____x___________",
        snareVelocity = "____4___________",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____5_______5___"
    ),
DrumPreset(
        id = "jazz-15_jazz_120_beat_4-4",
        displayName = "15_Jazz_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.32f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-fast-78_jazz-fast_290_beat_4-4",
        displayName = "78_Jazz Fast_290_Beat_4 4",
        originalBpm = 290,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____4_______2___"
    ),
DrumPreset(
        id = "jazz-fusion-112_jazz-fusion_96_beat_4-4",
        displayName = "112_Jazz Fusion_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "x_______________",
        kickVelocity =  "5_______________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "xx_xxxxxxxxxxxxx",
        hihatVelocity = "73_5821393139413"
    ),
DrumPreset(
        id = "jazz-fusion-113_jazz-fusion_96_beat_4-4",
        displayName = "113_Jazz Fusion_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.14f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________5___"
    ),
DrumPreset(
        id = "jazz-fusion-114_jazz-fusion_96_beat_4-4",
        displayName = "114_Jazz Fusion_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.4f,
        kickPattern =   "_______________x",
        kickVelocity =  "_______________4",
        snarePattern =  "_____xx_xxx_____",
        snareVelocity = "_____57_944_____",
        hihatPattern =  "_x______________",
        hihatVelocity = "_5______________"
    ),
DrumPreset(
        id = "jazz-klezmer-3_jazz-klezmer_152_beat_4-4",
        displayName = "3_Jazz Klezmer_152_Beat_4 4",
        originalBpm = 152,
        timeSignature = "4/4",
        grooveFactor = 0.07f,
        kickPattern =   "x___x_x___x_x___",
        kickVelocity =  "6___5_8___5_4___",
        snarePattern =  "x_____x_____x___",
        snareVelocity = "9_____9_____9___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-linear-4_jazz-linear_182_beat_4-4",
        displayName = "4_Jazz Linear_182_Beat_4 4",
        originalBpm = 182,
        timeSignature = "4/4",
        grooveFactor = 0.24f,
        kickPattern =   "x_______________",
        kickVelocity =  "5_______________",
        snarePattern =  "___________x__x_",
        snareVelocity = "___________1__2_",
        hihatPattern =  "____x_x_____x_x_",
        hihatVelocity = "____5_3_____6_4_"
    ),
DrumPreset(
        id = "jazz-linear-5_jazz-linear_128_beat_4-4",
        displayName = "5_Jazz Linear_128_Beat_4 4",
        originalBpm = 128,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "_______________x",
        kickVelocity =  "_______________4",
        snarePattern =  "____________xxx_",
        snareVelocity = "____________444_",
        hihatPattern =  "______________x_",
        hihatVelocity = "______________4_"
    ),
DrumPreset(
        id = "jazz-march-7_jazz-march_88_beat_4-4",
        displayName = "7_Jazz March_88_Beat_4 4",
        originalBpm = 88,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________xx",
        snareVelocity = "______________24",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-march-8_jazz-march_176_beat_4-4",
        displayName = "8_Jazz March_176_Beat_4 4",
        originalBpm = 176,
        timeSignature = "4/4",
        grooveFactor = 0.34f,
        kickPattern =   "x_______x_______",
        kickVelocity =  "4_______5_______",
        snarePattern =  "x___xxxxx___x_xx",
        snareVelocity = "7___33445___3_44",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-march-9_jazz-march_120_beat_4-4",
        displayName = "9_Jazz March_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.12f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "x_xxx_xxx_xxxxxx",
        snareVelocity = "6_344_334_333333",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-mediumfast-76_jazz-mediumfast_180_beat_4-4",
        displayName = "76_Jazz Mediumfast_180_Beat_4 4",
        originalBpm = 180,
        timeSignature = "4/4",
        grooveFactor = 0.31f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "__xx___x________",
        snareVelocity = "__11___2________",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____4_______7___"
    ),
DrumPreset(
        id = "jazz-mediumfast-77_jazz-mediumfast_180_beat_4-4",
        displayName = "77_Jazz Mediumfast_180_Beat_4 4",
        originalBpm = 180,
        timeSignature = "4/4",
        grooveFactor = 0.32f,
        kickPattern =   "_______________x",
        kickVelocity =  "_______________3",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____x______x____",
        hihatVelocity = "____5______6____"
    ),
DrumPreset(
        id = "jazz-swing-10_jazz-swing_110_beat_4-4",
        displayName = "10_Jazz Swing_110_Beat_4 4",
        originalBpm = 110,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "____x_______x___",
        kickVelocity =  "____5_______6___",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "jazz-swing-1_jazz-swing_124_beat_4-4",
        displayName = "1_Jazz Swing_124_Beat_4 4",
        originalBpm = 124,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____x_______x_x_",
        hihatVelocity = "____5_______5_3_"
    ),
DrumPreset(
        id = "jazz-swing-2_jazz-swing_215_beat_4-4",
        displayName = "2_Jazz Swing_215_Beat_4 4",
        originalBpm = 215,
        timeSignature = "4/4",
        grooveFactor = 0.34f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-12_latin_118_beat_4-4",
        displayName = "12_Latin_118_Beat_4 4",
        originalBpm = 118,
        timeSignature = "4/4",
        grooveFactor = 0.24f,
        kickPattern =   "x_______________",
        kickVelocity =  "4_______________",
        snarePattern =  "________x_x_____",
        snareVelocity = "________2_1_____",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____5_______6___"
    ),
DrumPreset(
        id = "latin-13_latin_118_beat_4-4",
        displayName = "13_Latin_118_Beat_4 4",
        originalBpm = 118,
        timeSignature = "4/4",
        grooveFactor = 0.25f,
        kickPattern =   "x_______________",
        kickVelocity =  "5_______________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____6_______6___"
    ),
DrumPreset(
        id = "latin-24_latin_84_beat_4-4",
        displayName = "24_Latin_84_Beat_4 4",
        originalBpm = 84,
        timeSignature = "4/4",
        grooveFactor = 0.09f,
        kickPattern =   "x__xx____x__x__x",
        kickVelocity =  "5__35____4__5__3",
        snarePattern =  "__x__x_x___x__x_",
        snareVelocity = "__9__8_8___9__9_",
        hihatPattern =  "__xx__x__x____x_",
        hihatVelocity = "__52__6__1____5_"
    ),
DrumPreset(
        id = "latin-ando-16_latin-ando_125_beat_3-4",
        displayName = "16_Latin Ando_125_Beat_3 4",
        originalBpm = 125,
        timeSignature = "3/4",
        grooveFactor = 0.18f,
        kickPattern =   "xx______x___x___",
        kickVelocity =  "31______3___3___",
        snarePattern =  "_x_x_x_x__xx_x_x",
        snareVelocity = "_1_7_6_4__73_2_8",
        hihatPattern =  "__x_x___x_______",
        hihatVelocity = "__2_5___4_______"
    ),
DrumPreset(
        id = "latin-bomba-12_latin-bomba_96_beat_4-4",
        displayName = "12_Latin Bomba_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "___________xxx__",
        snareVelocity = "___________511__",
        hihatPattern =  "xx__x___x___x___",
        hihatVelocity = "53__5___5___5___"
    ),
DrumPreset(
        id = "latin-bounce-28_latin-bounce_106_beat_4-4",
        displayName = "28_Latin Bounce_106_Beat_4 4",
        originalBpm = 106,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "5___5___5___5___",
        snarePattern =  "___x__xx___x__xx",
        snareVelocity = "___7__74___7__52",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__7___7___6___7_"
    ),
DrumPreset(
        id = "latin-bounce-29_latin-bounce_106_beat_4-4",
        displayName = "29_Latin Bounce_106_Beat_4 4",
        originalBpm = 106,
        timeSignature = "4/4",
        grooveFactor = 0.22f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "4___4___4___4___",
        snarePattern =  "___x__xx___x__xx",
        snareVelocity = "___7__74___6__93",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___5___6___6_"
    ),
DrumPreset(
        id = "latin-brazilian-2_latin-brazilian_101_beat_4-4",
        displayName = "2_Latin Brazilian_101_Beat_4 4",
        originalBpm = 101,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "____x_x_____xx__",
        kickVelocity =  "____3_1_____41__",
        snarePattern =  "_x_x_x__xx_xxx_x",
        snareVelocity = "_7_1_1__82_311_7",
        hihatPattern =  "__x___________x_",
        hihatVelocity = "__3___________3_"
    ),
DrumPreset(
        id = "latin-brazilian-3_latin-brazilian_101_beat_4-4",
        displayName = "3_Latin Brazilian_101_Beat_4 4",
        originalBpm = 101,
        timeSignature = "4/4",
        grooveFactor = 0.2f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________xxxxx___",
        snareVelocity = "________71183___",
        hihatPattern =  "________x___x___",
        hihatVelocity = "________6___8___"
    ),
DrumPreset(
        id = "latin-brazilian-4_latin-brazilian_92_beat_4-4",
        displayName = "4_Latin Brazilian_92_Beat_4 4",
        originalBpm = 92,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "xx_x_x_x_x__x_x_",
        kickVelocity =  "44_4_4_4_5__5_4_",
        snarePattern =  "xx_x_x_x_x__x_x_",
        snareVelocity = "99_9_9_9_9__9_9_",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-brazilian-baiao-145_latin-brazilian-baiao_95_beat_4-4",
        displayName = "145_Latin Brazilian Baiao_95_Beat_4 4",
        originalBpm = 95,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "x__x____x__x____",
        kickVelocity =  "3__4____4__4____",
        snarePattern =  "___x__x____x__x_",
        snareVelocity = "___1__3____1__2_",
        hihatPattern =  "__x_x___xx__xx__",
        hihatVelocity = "__4_2___22__32__"
    ),
DrumPreset(
        id = "latin-brazilian-baiao-146_latin-brazilian-baiao_95_beat_4-4",
        displayName = "146_Latin Brazilian Baiao_95_Beat_4 4",
        originalBpm = 95,
        timeSignature = "4/4",
        grooveFactor = 0.33f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________x_",
        snareVelocity = "______________2_",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________2___"
    ),
DrumPreset(
        id = "latin-brazilian-baiao-20_latin-brazilian-baiao_110_beat_4-4",
        displayName = "20_Latin Brazilian Baiao_110_Beat_4 4",
        originalBpm = 110,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "xx_x____x__x____",
        kickVelocity =  "11_3____3__3____",
        snarePattern =  "___xx_x_x__xx_x_",
        snareVelocity = "___21_7_1__11_6_",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__4___5___4___4_"
    ),
DrumPreset(
        id = "latin-brazilian-bossa-1_latin-brazilian-bossa_127_beat_4-4",
        displayName = "1_Latin Brazilian Bossa_127_Beat_4 4",
        originalBpm = 127,
        timeSignature = "4/4",
        grooveFactor = 0.12f,
        kickPattern =   "x_____x_xx____x_",
        kickVelocity =  "3_____1_31____3_",
        snarePattern =  "____x_____x_____",
        snareVelocity = "____1_____2_____",
        hihatPattern =  "__x_x_______x___",
        hihatVelocity = "__2_5_______5___"
    ),
DrumPreset(
        id = "latin-brazilian-bossa-2_latin-brazilian-bossa_127_beat_4-4",
        displayName = "2_Latin Brazilian Bossa_127_Beat_4 4",
        originalBpm = 127,
        timeSignature = "4/4",
        grooveFactor = 0.28f,
        kickPattern =   "______x_x_____x_",
        kickVelocity =  "______2_1_____1_",
        snarePattern =  "__________xxxxx_",
        snareVelocity = "__________43211_",
        hihatPattern =  "____x___x__x___x",
        hihatVelocity = "____5___2__5___2"
    ),
DrumPreset(
        id = "latin-brazilian-frevo-22_latin-brazilian-frevo_133_beat_4-4",
        displayName = "22_Latin Brazilian Frevo_133_Beat_4 4",
        originalBpm = 133,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "xx__x___x___x___",
        kickVelocity =  "41__3___3___3___",
        snarePattern =  "xxxxxxxxxxxxxxxx",
        snareVelocity = "8337839339346433",
        hihatPattern =  "__x_x_x_x_xx__xx",
        hihatVelocity = "__7_5_7_5_72__72"
    ),
DrumPreset(
        id = "latin-brazilian-ijexa-19_latin-brazilian-ijexa_108_beat_4-4",
        displayName = "19_Latin Brazilian Ijexa_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "____x_x_____x_x_",
        kickVelocity =  "____3_3_____3_3_",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "4___4___5___6___"
    ),
DrumPreset(
        id = "latin-brazilian-ijexa-20_latin-brazilian-ijexa_108_beat_4-4",
        displayName = "20_Latin Brazilian Ijexa_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "____xxx_____xx__",
        kickVelocity =  "____314_____41__",
        snarePattern =  "_____xx_xx_xxxxx",
        snareVelocity = "_____31_73_62118",
        hihatPattern =  "__x_______x___x_",
        hihatVelocity = "__4_______3___4_"
    ),
DrumPreset(
        id = "latin-brazilian-ijexa-21_latin-brazilian-ijexa_108_beat_4-4",
        displayName = "21_Latin Brazilian Ijexa_108_Beat_4 4",
        originalBpm = 108,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "____x_______x_x_",
        kickVelocity =  "____1_______3_1_",
        snarePattern =  "_x_x_x_x_x_x_xx_",
        snareVelocity = "_2_5_2_8_2_5_21_",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__3___3___3___4_"
    ),
DrumPreset(
        id = "latin-brazilian-maracatu-6_latin-brazilian-maracatu_96_beat_4-4",
        displayName = "6_Latin Brazilian Maracatu_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.42f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________4___"
    ),
DrumPreset(
        id = "latin-brazilian-maracatu-7_latin-brazilian-maracatu_96_beat_4-4",
        displayName = "7_Latin Brazilian Maracatu_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "x________x___x_x",
        kickVelocity =  "3________3___3_2",
        snarePattern =  "xxxxxxxxxxxxxxxx",
        snareVelocity = "3334434334333433",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___3___5___5_"
    ),
DrumPreset(
        id = "latin-brazilian-samba-17_latin-brazilian-samba_110_beat_4-4",
        displayName = "17_Latin Brazilian Samba_110_Beat_4 4",
        originalBpm = 110,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________xx",
        snareVelocity = "______________11",
        hihatPattern =  "x____x__x___x_x_",
        hihatVelocity = "3____4__4___6_5_"
    ),
DrumPreset(
        id = "latin-brazilian-samba-18_latin-brazilian-samba_93_beat_4-4",
        displayName = "18_Latin Brazilian Samba_93_Beat_4 4",
        originalBpm = 93,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "_____x__x___x___",
        hihatVelocity = "_____3__4___3___"
    ),
DrumPreset(
        id = "latin-brazilian-samba-3_latin-brazilian-samba_89_beat_4-4",
        displayName = "3_Latin Brazilian Samba_89_Beat_4 4",
        originalBpm = 89,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "x__xx__xx__xx__x",
        kickVelocity =  "3__34__33__24__2",
        snarePattern =  "xxxx_xxx_xxx_xxx",
        snareVelocity = "3343_235_613_335",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___5___4___3_"
    ),
DrumPreset(
        id = "latin-brazilian-sambareggae-10_latin-brazilian-sambareggae_96_beat_4-4",
        displayName = "10_Latin Brazilian Sambareggae_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.22f,
        kickPattern =   "____x___x___x___",
        kickVelocity =  "____1___1___1___",
        snarePattern =  "_xxx_x_x_xxx____",
        snareVelocity = "_147_3_3_336____",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___4___5___3_"
    ),
DrumPreset(
        id = "latin-brazilian-sambareggae-11_latin-brazilian-sambareggae_96_beat_4-4",
        displayName = "11_Latin Brazilian Sambareggae_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.11f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "3___3___3___1___",
        snarePattern =  "_xxx_x_x_xx_____",
        snareVelocity = "_236_3_3_34_____",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___4___4___3_"
    ),
DrumPreset(
        id = "latin-brazilian-sambareggae-12_latin-brazilian-sambareggae_96_beat_4-4",
        displayName = "12_Latin Brazilian Sambareggae_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "3___3___3___4___",
        snarePattern =  "_xxx_x_x_xx_____",
        snareVelocity = "_246_2_2_24_____",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__4___5___6___6_"
    ),
DrumPreset(
        id = "latin-brazilian-songo-14_latin-brazilian-songo_112_beat_4-4",
        displayName = "14_Latin Brazilian Songo_112_Beat_4 4",
        originalBpm = 112,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "xx_x__x____x__x_",
        kickVelocity =  "31_3__3____3__3_",
        snarePattern =  "___x_____x_x_x__",
        snareVelocity = "___1_____6_3_2__",
        hihatPattern =  "x_x_________x___",
        hihatVelocity = "2_2_________2___"
    ),
DrumPreset(
        id = "latin-brazilian-songo-23_latin-brazilian-songo_120_beat_4-4",
        displayName = "23_Latin Brazilian Songo_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "x__x_______x____",
        kickVelocity =  "4__3_______2____",
        snarePattern =  "xx_xxxx_xx_xxxxx",
        snareVelocity = "32_2121_19_31118",
        hihatPattern =  "__x___x_________",
        hihatVelocity = "__5___5_________"
    ),
DrumPreset(
        id = "latin-brazilian-songo-24_latin-brazilian-songo_120_beat_4-4",
        displayName = "24_Latin Brazilian Songo_120_Beat_4 4",
        originalBpm = 120,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "x_______________",
        kickVelocity =  "3_______________",
        snarePattern =  "_xxxxxxxxxxxx__x",
        snareVelocity = "_135633862489__1",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-chacarera-1_latin-chacarera_157_beat_3-4",
        displayName = "1_Latin Chacarera_157_Beat_3 4",
        originalBpm = 157,
        timeSignature = "3/4",
        grooveFactor = 0.1f,
        kickPattern =   "____________x___",
        kickVelocity =  "____________4___",
        snarePattern =  "______x_________",
        snareVelocity = "______7_________",
        hihatPattern =  "x___x___x___x_x_",
        hihatVelocity = "4___5___5___6_3_"
    ),
DrumPreset(
        id = "latin-chacarera-2_latin-chacarera_118_beat_4-4",
        displayName = "2_Latin Chacarera_118_Beat_4 4",
        originalBpm = 118,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "______x__x_____x",
        kickVelocity =  "______3__4_____4",
        snarePattern =  "x___x___________",
        snareVelocity = "9___8___________",
        hihatPattern =  "______x_xxx_xx_x",
        hihatVelocity = "______3_333_32_2"
    ),
DrumPreset(
        id = "latin-chacarera-3_latin-chacarera_118_beat_4-4",
        displayName = "3_Latin Chacarera_118_Beat_4 4",
        originalBpm = 118,
        timeSignature = "4/4",
        grooveFactor = 0.25f,
        kickPattern =   "______x__x____x_",
        kickVelocity =  "______4__4____4_",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____xxx_xx_xxx_x",
        hihatVelocity = "____634_44_353_4"
    ),
DrumPreset(
        id = "latin-dominican-merengue-9_latin-dominican-merengue_130_beat_4-4",
        displayName = "9_Latin Dominican Merengue_130_Beat_4 4",
        originalBpm = 130,
        timeSignature = "4/4",
        grooveFactor = 0.14f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "2___2___2___2___",
        snarePattern =  "___x__x___x_____",
        snareVelocity = "___5__5___5_____",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__2___3___3___2_"
    ),
DrumPreset(
        id = "latin-merengue-9_latin-merengue_158_beat_4-4",
        displayName = "9_Latin Merengue_158_Beat_4 4",
        originalBpm = 158,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "x___x__x____x__x",
        kickVelocity =  "9___4__4____4__6",
        snarePattern =  "___xx_xxx_x_____",
        snareVelocity = "___89_687_9_____",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-reggaeton-79_latin-reggaeton_90_beat_4-4",
        displayName = "79_Latin Reggaeton_90_Beat_4 4",
        originalBpm = 90,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "____________x___",
        kickVelocity =  "____________5___",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-samba-28_latin-samba_116_beat_4-4",
        displayName = "28_Latin Samba_116_Beat_4 4",
        originalBpm = 116,
        timeSignature = "4/4",
        grooveFactor = 0.31f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "______________x_",
        hihatVelocity = "______________3_"
    ),
DrumPreset(
        id = "latin-venezuelan-joropo-15_latin-venezuelan-joropo_80_beat_4-4",
        displayName = "15_Latin Venezuelan Joropo_80_Beat_4 4",
        originalBpm = 80,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "x__xx__xx__xx__x",
        kickVelocity =  "1__33__34__31__3",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "latin-venezuelan-merengue-8_latin-venezuelan-merengue_162_beat_5-8",
        displayName = "8_Latin Venezuelan Merengue_162_Beat_5 8",
        originalBpm = 162,
        timeSignature = "5/8",
        grooveFactor = 0.1f,
        kickPattern =   "____x___x_____x_",
        kickVelocity =  "____3___3_____3_",
        snarePattern =  "x_x_x_x_x___x_x_",
        snareVelocity = "5_3_3_4_3___3_3_",
        hihatPattern =  "______x_________",
        hihatVelocity = "______3_________"
    ),
DrumPreset(
        id = "latin-venezuelan-sangueo-1_latin-venezuelan-sangueo_101_beat_4-4",
        displayName = "1_Latin Venezuelan Sangueo_101_Beat_4 4",
        originalBpm = 101,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "xx_x_x_x_x_x____",
        kickVelocity =  "22_3_3_3_3_3____",
        snarePattern =  "xx__x__x_______x",
        snareVelocity = "21__7__1_______4",
        hihatPattern =  "____x__x______x_",
        hihatVelocity = "____4__3______4_"
    ),
DrumPreset(
        id = "middleeastern-19_middleeastern_126_beat_4-4",
        displayName = "19_Middleeastern_126_Beat_4 4",
        originalBpm = 126,
        timeSignature = "4/4",
        grooveFactor = 0.14f,
        kickPattern =   "x_____x_x_______",
        kickVelocity =  "3_____2_3_______",
        snarePattern =  "__x____________x",
        snareVelocity = "__6____________2",
        hihatPattern =  "______x___x_x___",
        hihatVelocity = "______3___3_6___"
    ),
DrumPreset(
        id = "neworleans-chacha-8_neworleans-chacha_124_beat_4-4",
        displayName = "8_Neworleans Chacha_124_Beat_4 4",
        originalBpm = 124,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________x___xxxx",
        snareVelocity = "________9___9544",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "2___6___3___5___"
    ),
DrumPreset(
        id = "neworleans-funk-10_neworleans-funk_82_beat_4-4",
        displayName = "10_Neworleans Funk_82_Beat_4 4",
        originalBpm = 82,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "x__x_x_xx__x____",
        kickVelocity =  "5__4_4_35__4____",
        snarePattern =  "x__x__x__x__x___",
        snareVelocity = "9__7__8__7__9___",
        hihatPattern =  "_x_x_x_x_x______",
        hihatVelocity = "_2_4_2_2_3______"
    ),
DrumPreset(
        id = "neworleans-funk-11_neworleans-funk_82_beat_4-4",
        displayName = "11_Neworleans Funk_82_Beat_4 4",
        originalBpm = 82,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "x__x_x_xx_xx____",
        kickVelocity =  "6__5_4_36_54____",
        snarePattern =  "x__xx_x__x__x___",
        snareVelocity = "9__94_9__8__9___",
        hihatPattern =  "_x_x_x__________",
        hihatVelocity = "_2_5_3__________"
    ),
DrumPreset(
        id = "neworleans-funk-82_neworleans-funk_84_beat_4-4",
        displayName = "82_Neworleans Funk_84_Beat_4 4",
        originalBpm = 84,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "__________x____x",
        kickVelocity =  "__________4____3",
        snarePattern =  "____x__xx____xx_",
        snareVelocity = "____7__21____68_",
        hihatPattern =  "______x_______x_",
        hihatVelocity = "______4_______5_"
    ),
DrumPreset(
        id = "neworleans-secondline-100_neworleans-secondline_94_beat_4-4",
        displayName = "100_Neworleans Secondline_94_Beat_4 4",
        originalBpm = 94,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "___________x____",
        kickVelocity =  "___________3____",
        snarePattern =  "_______x_xx__xxx",
        snareVelocity = "_______7_34__323",
        hihatPattern =  "________x_x___x_",
        hihatVelocity = "________5_2___6_"
    ),
DrumPreset(
        id = "neworleans-secondline-6_neworleans-secondline_99_beat_4-4",
        displayName = "6_Neworleans Secondline_99_Beat_4 4",
        originalBpm = 99,
        timeSignature = "4/4",
        grooveFactor = 0.22f,
        kickPattern =   "x_______________",
        kickVelocity =  "3_______________",
        snarePattern =  "xxx_xxxxx__x_xx_",
        snareVelocity = "534_24333__3_54_",
        hihatPattern =  "__x___________x_",
        hihatVelocity = "__4___________3_"
    ),
DrumPreset(
        id = "neworleans-secondline-7_neworleans-secondline_124_beat_4-4",
        displayName = "7_Neworleans Secondline_124_Beat_4 4",
        originalBpm = 124,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "x_________x_____",
        kickVelocity =  "3_________3_____",
        snarePattern =  "xx____xxxx__xxxx",
        snareVelocity = "53____8222__6332",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "6___6___6___6___"
    ),
DrumPreset(
        id = "neworleans-shuffle-9_neworleans-shuffle_104_beat_4-4",
        displayName = "9_Neworleans Shuffle_104_Beat_4 4",
        originalBpm = 104,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "xx_x__x_xx_x__x_",
        kickVelocity =  "41_3__3_41_3__4_",
        snarePattern =  "xxxxxxxxxxxxxxxx",
        snareVelocity = "4453247434643373",
        hihatPattern =  "__x___x___x___x_",
        hihatVelocity = "__5___5___5___5_"
    ),
DrumPreset(
        id = "pop-100_pop_142_beat_4-4",
        displayName = "100_Pop_142_Beat_4 4",
        originalBpm = 142,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "______xx________",
        kickVelocity =  "______45________",
        snarePattern =  "xx_______xxxxxxx",
        snareVelocity = "97_______9547668",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "pop-101_pop_142_beat_4-4",
        displayName = "101_Pop_142_Beat_4 4",
        originalBpm = 142,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "____x___x___x___",
        hihatVelocity = "____4___4___5___"
    ),
DrumPreset(
        id = "pop-102_pop_132_beat_4-4",
        displayName = "102_Pop_132_Beat_4 4",
        originalBpm = 132,
        timeSignature = "4/4",
        grooveFactor = 0.29f,
        kickPattern =   "______x_x____x__",
        kickVelocity =  "______3_9____5__",
        snarePattern =  "_xxxx_x_____x__x",
        snareVelocity = "_3399_3_____9__1",
        hihatPattern =  "__________x_____",
        hihatVelocity = "__________1_____"
    ),
DrumPreset(
        id = "pop-groove7-7_pop-groove7_138_beat_4-4",
        displayName = "7_Pop Groove7_138_Beat_4 4",
        originalBpm = 138,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x_______x_______",
        kickVelocity =  "3_______3_______",
        snarePattern =  "____x__x____x___",
        snareVelocity = "____9__1____8___",
        hihatPattern =  "____x_x___x_____",
        hihatVelocity = "____2_2___1_____"
    ),
DrumPreset(
        id = "pop-soft-11_pop-soft_83_beat_4-4",
        displayName = "11_Pop Soft_83_Beat_4 4",
        originalBpm = 83,
        timeSignature = "4/4",
        grooveFactor = 0.08f,
        kickPattern =   "x_____x_________",
        kickVelocity =  "3_____3_________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "x_x_x___x_x_x_x_",
        hihatVelocity = "4_1_4___5_1_5_1_"
    ),
DrumPreset(
        id = "punk-32_punk_140_beat_4-4",
        displayName = "32_Punk_140_Beat_4 4",
        originalBpm = 140,
        timeSignature = "4/4",
        grooveFactor = 0.09f,
        kickPattern =   "____x___x_______",
        kickVelocity =  "____4___3_______",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "punk-33_punk_128_beat_4-4",
        displayName = "33_Punk_128_Beat_4 4",
        originalBpm = 128,
        timeSignature = "4/4",
        grooveFactor = 0.21f,
        kickPattern =   "_x_x_x_x_x_x_x_x",
        kickVelocity =  "_2_3_2_3_3_3_3_3",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "punk-34_punk_128_beat_4-4",
        displayName = "34_Punk_128_Beat_4 4",
        originalBpm = 128,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "_x_x_x_x_x_x_x_x",
        kickVelocity =  "_3_3_3_3_3_3_3_3",
        snarePattern =  "__________x___x_",
        snareVelocity = "__________6___7_",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "reggae-184_reggae_78_beat_4-4",
        displayName = "184_Reggae_78_Beat_4 4",
        originalBpm = 78,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "___________x__x_",
        snareVelocity = "___________3__7_",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "reggae-slow-201_reggae-slow_64_beat_4-4",
        displayName = "201_Reggae Slow_64_Beat_4 4",
        originalBpm = 64,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________x_",
        snareVelocity = "______________2_",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________2___"
    ),
DrumPreset(
        id = "rock-10_rock_100_beat_4-4",
        displayName = "10_Rock_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.3f,
        kickPattern =   "____x___________",
        kickVelocity =  "____1___________",
        snarePattern =  "________________",
        snareVelocity = "________________",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-11_rock_100_beat_4-4",
        displayName = "11_Rock_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.07f,
        kickPattern =   "x_________xx__x_",
        kickVelocity =  "9_________99__9_",
        snarePattern =  "____x__x_x__x___",
        snareVelocity = "____9__8_9__9___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-12_rock_100_beat_4-4",
        displayName = "12_Rock_100_Beat_4 4",
        originalBpm = 100,
        timeSignature = "4/4",
        grooveFactor = 0.18f,
        kickPattern =   "x_______________",
        kickVelocity =  "9_______________",
        snarePattern =  "____x__x_x_x____",
        snareVelocity = "____9__9_9_9____",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-folk-10_rock-folk_90_beat_4-4",
        displayName = "10_Rock Folk_90_Beat_4 4",
        originalBpm = 90,
        timeSignature = "4/4",
        grooveFactor = 0.13f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "______________xx",
        snareVelocity = "______________23",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-groove8-8_rock-groove8_65_beat_4-4",
        displayName = "8_Rock Groove8_65_Beat_4 4",
        originalBpm = 65,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "x______xx_______",
        kickVelocity =  "1______21_______",
        snarePattern =  "____x_______xx__",
        snareVelocity = "____4_______22__",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-halftime-202_rock-halftime_140_beat_4-4",
        displayName = "202_Rock Halftime_140_Beat_4 4",
        originalBpm = 140,
        timeSignature = "4/4",
        grooveFactor = 0.26f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________x_______",
        snareVelocity = "________9_______",
        hihatPattern =  "____________x___",
        hihatVelocity = "____________3___"
    ),
DrumPreset(
        id = "rock-indie-39_rock-indie_104_beat_4-4",
        displayName = "39_Rock Indie_104_Beat_4 4",
        originalBpm = 104,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "__xx__x_x_______",
        kickVelocity =  "__43__4_6_______",
        snarePattern =  "_x___x______x___",
        snareVelocity = "_4___4______9___",
        hihatPattern =  "x_x___x___xx__x_",
        hihatVelocity = "6_3___3___32__3_"
    ),
DrumPreset(
        id = "rock-indie-39_rock-indie_63_beat_4-4",
        displayName = "39_Rock Indie_63_Beat_4 4",
        originalBpm = 63,
        timeSignature = "4/4",
        grooveFactor = 0.05f,
        kickPattern =   "x__x_x_xx__x___x",
        kickVelocity =  "2__1_2_11__2___2",
        snarePattern =  "____________x___",
        snareVelocity = "____________7___",
        hihatPattern =  "xxxxxxxxxxxxxxxx",
        hihatVelocity = "5242525252536362"
    ),
DrumPreset(
        id = "rock-indie-40_rock-indie_104_beat_4-4",
        displayName = "40_Rock Indie_104_Beat_4 4",
        originalBpm = 104,
        timeSignature = "4/4",
        grooveFactor = 0.07f,
        kickPattern =   "x_xx__x_x_______",
        kickVelocity =  "1_43__4_5_______",
        snarePattern =  "_x___x______x___",
        snareVelocity = "_3___5______9___",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "5___5___5___5___"
    ),
DrumPreset(
        id = "rock-prog-110_rock-prog_190_beat_4-4",
        displayName = "110_Rock Prog_190_Beat_4 4",
        originalBpm = 190,
        timeSignature = "4/4",
        grooveFactor = 0.03f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________x_______",
        snareVelocity = "________9_______",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-prog-111_rock-prog_110_beat_5-4",
        displayName = "111_Rock Prog_110_Beat_5 4",
        originalBpm = 110,
        timeSignature = "5/4",
        grooveFactor = 0.22f,
        kickPattern =   "x_________x_____",
        kickVelocity =  "4_________4_____",
        snarePattern =  "_________x_x___x",
        snareVelocity = "_________1_1___8",
        hihatPattern =  "x___x___x___x__x",
        hihatVelocity = "3___5___6___6__3"
    ),
DrumPreset(
        id = "rock-prog-1_rock-prog_125_beat_4-4",
        displayName = "1_Rock Prog_125_Beat_4 4",
        originalBpm = 125,
        timeSignature = "4/4",
        grooveFactor = 0.17f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "___________xxx__",
        snareVelocity = "___________893__",
        hihatPattern =  "x___x___x___x___",
        hihatVelocity = "6___6___6___6___"
    ),
DrumPreset(
        id = "rock-rockabilly-3_rock-rockabilly_200_beat_4-4",
        displayName = "3_Rock Rockabilly_200_Beat_4 4",
        originalBpm = 200,
        timeSignature = "4/4",
        grooveFactor = 0.28f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "___________xx___",
        snareVelocity = "___________79___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "rock-shuffle-1_rock-shuffle_85_beat_4-4",
        displayName = "1_Rock Shuffle_85_Beat_4 4",
        originalBpm = 85,
        timeSignature = "4/4",
        grooveFactor = 0.14f,
        kickPattern =   "x_______x___xx__",
        kickVelocity =  "4_______4___33__",
        snarePattern =  "_xxxxxxxxxxxxxxx",
        snareVelocity = "_142324432423243",
        hihatPattern =  "__x_xxx_xxxxxxx_",
        hihatVelocity = "__3_315_4151314_"
    ),
DrumPreset(
        id = "rock-shuffle-20_rock-shuffle_112_beat_4-4",
        displayName = "20_Rock Shuffle_112_Beat_4 4",
        originalBpm = 112,
        timeSignature = "4/4",
        grooveFactor = 0.2f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "5___5___5___6___",
        snarePattern =  "____x_______x___",
        snareVelocity = "____9_______8___",
        hihatPattern =  "x____x__________",
        hihatVelocity = "5____2__________"
    ),
DrumPreset(
        id = "rock-shuffle-21_rock-shuffle_112_beat_4-4",
        displayName = "21_Rock Shuffle_112_Beat_4 4",
        originalBpm = 112,
        timeSignature = "4/4",
        grooveFactor = 0.26f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "5___5___5___5___",
        snarePattern =  "____x_____x_x_x_",
        snareVelocity = "____8_____6_9_9_",
        hihatPattern =  "x_x___x__x____xx",
        hihatVelocity = "3_3___5__4____63"
    ),
DrumPreset(
        id = "soul-11_soul_96_beat_4-4",
        displayName = "11_Soul_96_Beat_4 4",
        originalBpm = 96,
        timeSignature = "4/4",
        grooveFactor = 0.1f,
        kickPattern =   "x______________x",
        kickVelocity =  "1______________2",
        snarePattern =  "_x__x____xx_x___",
        snareVelocity = "_2__8____11_8___",
        hihatPattern =  "__________x_____",
        hihatVelocity = "__________2_____"
    ),
DrumPreset(
        id = "soul-130_soul_105_beat_4-4",
        displayName = "130_Soul_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.23f,
        kickPattern =   "x_______x_x_____",
        kickVelocity =  "3_______2_3_____",
        snarePattern =  "_____x_x_x__xx_x",
        snareVelocity = "_____3_3_2__82_3",
        hihatPattern =  "x_x_x_xx____x__x",
        hihatVelocity = "4_6_5_45____4__5"
    ),
DrumPreset(
        id = "soul-131_soul_105_beat_4-4",
        displayName = "131_Soul_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.15f,
        kickPattern =   "x___x___x___x___",
        kickVelocity =  "4___4___3___4___",
        snarePattern =  "____x__x_x__x__x",
        snareVelocity = "____8__2_3__8__1",
        hihatPattern =  "x___x_x_x___x___",
        hihatVelocity = "3___5_7_2___4___"
    ),
DrumPreset(
        id = "soul-groove10-10_soul-groove10_102_beat_4-4",
        displayName = "10_Soul Groove10_102_Beat_4 4",
        originalBpm = 102,
        timeSignature = "4/4",
        grooveFactor = 0.19f,
        kickPattern =   "x_________x____x",
        kickVelocity =  "3_________3____2",
        snarePattern =  "_xx_x_x_xxx_x___",
        snareVelocity = "_11_8_1_111_8___",
        hihatPattern =  "__________x___x_",
        hihatVelocity = "__________3___4_"
    ),
DrumPreset(
        id = "soul-groove3-3_soul-groove3_86_beat_4-4",
        displayName = "3_Soul Groove3_86_Beat_4 4",
        originalBpm = 86,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x__x___x_xx__x_x",
        kickVelocity =  "3__3___3_23__3_2",
        snarePattern =  "__x_x_____xxx___",
        snareVelocity = "__1_7_____117___",
        hihatPattern =  "_______________x",
        hihatVelocity = "_______________3"
    ),
DrumPreset(
        id = "soul-groove4-4_soul-groove4_80_beat_4-4",
        displayName = "4_Soul Groove4_80_Beat_4 4",
        originalBpm = 80,
        timeSignature = "4/4",
        grooveFactor = 0.06f,
        kickPattern =   "x_______x_______",
        kickVelocity =  "3_______3_______",
        snarePattern =  "____x_____x_x___",
        snareVelocity = "____7_____1_9___",
        hihatPattern =  "________________",
        hihatVelocity = "________________"
    ),
DrumPreset(
        id = "soul-groove9-9_soul-groove9_105_beat_4-4",
        displayName = "9_Soul Groove9_105_Beat_4 4",
        originalBpm = 105,
        timeSignature = "4/4",
        grooveFactor = 0.05f,
        kickPattern =   "x_________x____x",
        kickVelocity =  "4_________4____2",
        snarePattern =  "____x_______x___",
        snareVelocity = "____8_______8___",
        hihatPattern =  "__________x_____",
        hihatVelocity = "__________3_____"
    ),
DrumPreset(
        id = "soul-motown-106_soul-motown_104_beat_4-4",
        displayName = "106_Soul Motown_104_Beat_4 4",
        originalBpm = 104,
        timeSignature = "4/4",
        grooveFactor = 0.2f,
        kickPattern =   "x_____x_x_______",
        kickVelocity =  "3_____2_2_______",
        snarePattern =  "____x___________",
        snareVelocity = "____5___________",
        hihatPattern =  "____x_______x___",
        hihatVelocity = "____4_______4___"
    ),
DrumPreset(
        id = "soul-motown-108_soul-motown_104_beat_4-4",
        displayName = "108_Soul Motown_104_Beat_4 4",
        originalBpm = 104,
        timeSignature = "4/4",
        grooveFactor = 0.33f,
        kickPattern =   "________________",
        kickVelocity =  "________________",
        snarePattern =  "________x_xxxx__",
        snareVelocity = "________4_3594__",
        hihatPattern =  "____x___x__x____",
        hihatVelocity = "____3___4__5____"
    ),
DrumPreset(
        id = "soul-motown-54_soul-motown_148_beat_4-4",
        displayName = "54_Soul Motown_148_Beat_4 4",
        originalBpm = 148,
        timeSignature = "4/4",
        grooveFactor = 0.16f,
        kickPattern =   "x_____x___x___x_",
        kickVelocity =  "5_____4___3___4_",
        snarePattern =  "x___x___x___x___",
        snareVelocity = "9___8___6___7___",
        hihatPattern =  "__________x___x_",
        hihatVelocity = "__________2___2_"
    )

)

fun getGenreFromPresetId(id: String): String {
    return id.split("-").first()
}

fun getPresetsByGenre(genre: Genre, lockToGenre: Boolean = true): List<DrumPreset> {
    if (!lockToGenre) return allDrumPresets
    
    val validFolderGenres = when (genre) {
        Genre.ROCK -> listOf("rock", "rock-shuffle", "rock-indie", "rock-prog", "rock-rockabilly", "rock-folk", "rock-halftime", "rock-groove8")
        Genre.BLUES -> listOf("blues", "blues-shuffle")
        Genre.COUNTRY -> listOf("country")
        Genre.FUNK -> listOf("funk", "funk-fast", "funk-groove1", "funk-groove2", "funk-groove5", "funk-latin", "funk-purdieshuffle", "funk-rock")
        Genre.JAZZ -> listOf("jazz", "jazz-fast", "jazz-funk", "jazz-fusion", "jazz-klezmer", "jazz-linear", "jazz-march", "jazz-mediumfast", "jazz-swing")
    }
    
    return allDrumPresets.filter { preset ->
        val presetGenre = getGenreFromPresetId(preset.id)
        validFolderGenres.contains(presetGenre)
    }
}

fun getAllGenres(): List<String> {
    return allDrumPresets.map { getGenreFromPresetId(it.id) }.distinct().sorted()
}

fun getRandomPresetForGenre(genre: Genre, lockToGenre: Boolean = true): DrumPreset? {
    return getPresetsByGenre(genre, lockToGenre).randomOrNull()
}

fun getPresetsByTempo(minBpm: Int, maxBpm: Int): List<DrumPreset> {
    return allDrumPresets.filter { it.originalBpm in minBpm..maxBpm }
}

fun getPresetsByGroove(minGroove: Float, maxGroove: Float): List<DrumPreset> {
    return allDrumPresets.filter { it.grooveFactor in minGroove..maxGroove }
}

object DrumPresetStats {
    val totalPresets = allDrumPresets.size
    val uniqueGenres = getAllGenres().size
    val genreCounts = allDrumPresets.groupingBy { getGenreFromPresetId(it.id) }.eachCount().toSortedMap()
}
